# Change these first 
owner: BabsyIT # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
#  - name: Babsy
#    url: https://www.babsy.ch
#    assignees:
#      - Oliver-Babsy
#      - stefan-ffr
#  - name: Babsy
#    url: https://babsy.ch/
#    icon: https://babsy.ch/wp-content/uploads/2021/12/cropped-babsy-logo-1.png
#    assignees:
#      - Oliver-Babsy
#      - stefan-ffr
#      - miran55
  - name: Babsy Verein
    url: https://verein.babsy.ch
    assignees:
      - Oliver-Babsy
      - stefan-ffr
      - miran55
  - name: Babsy Server dashboard-api.babsy.ch
    check: "tcp-ping"
    url: dashboard-api.babsy.ch
    port: 80
    assignees:
      - Oliver-Babsy
      - stefan-ffr
      - miran55
  - name: Babsy Server docker1.infra.babsy.ch
    check: "tcp-ping"
    url: docker1.infra.babsy.ch
    port: 80
    assignees:
      - Oliver-Babsy
      - stefan-ffr
      - miran55
  - name: Babsy Jitsi
    url: https://jitsi.babsy.ch
    assignees:
      - stefan-ffr
      - miran55
  - name: Babsy Bitwarden Passwordmanager
    url: https://bitwarden.babsy.ch
    assignees:
      - stefan-ffr
      - Oliver-Babsy
      - miran55
  - name: Babsy Newslettertool Listmonk
    url: http://newsletter.babsy.ch
    assignees:
      - stefan-ffr
      - Oliver-Babsy
      - miran55
  - name: Babsy Service E-Mail Server Webinterface
    url: https://mail.service.babsy.ch
    assignees:
      - stefan-ffr
      - miran55
  - name: Babsy Service E-Mail Server SMTP
    check: "tcp-ping"
    url: mail.service.babsy.ch
    port: 25
    assignees:
      - stefan-ffr
  - name: Babsy Service E-Mail Server SMTPS
    check: "tcp-ping"
    url: mail.service.babsy.ch
    port: 465
    assignees:
      - stefan-ffr
      - miran55
  - name: Babsy Service E-Mail Server Submission
    check: "tcp-ping"
    url: mail.service.babsy.ch
    port: 587
    assignees:
      - stefan-ffr
      - miran55
  - name: Babsy Service E-Mail Server IMAP
    check: "tcp-ping"
    url: mail.service.babsy.ch
    port: 143
    assignees:
      - stefan-ffr
      - miran55
  - name: Babsy Service E-Mail Server IMAPS
    check: "tcp-ping"
    url: mail.service.babsy.ch
    port: 993
    assignees:
      - stefan-ffr
      - miran55
  - name: Babsy Service E-Mail Server POP3
    check: "tcp-ping"
    url: mail.service.babsy.ch
    port: 110
    assignees:
      - stefan-ffr
      - miran55
  - name: Babsy Service E-Mail Server POP3S
    check: "tcp-ping"
    url: mail.service.babsy.ch
    port: 995
    assignees:
      - stefan-ffr
      - miran55
  - name: Babsy Service E-Mail Server Dovecot ManageSieve
    check: "tcp-ping"
    url: mail.service.babsy.ch
    port: 4190
    assignees:
      - stefan-ffr
      - miran55
 # - name: Babsy Test Website
 #   url: https://website.test.babsy.ch
 #   assignees:
 #    - stefan-ffr
 #    - miran55
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.babsy.ch
  # baseUrl: /uptime
  logoUrl: https://babsy.ch/wp-content/uploads/2021/12/cropped-babsy-logo-1.png
  name: Babsy-Uptime Monitoring
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the status page for Babsy
  navbar:
    - title: Babsy
      href: https://www.babsy.ch
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
